- name: update apt cache
  apt:
    update_cache=yes

- name: install apt packages
  apt:
    pkg={{ item }}
  with_items:
    - apache2
    - git
    - libapache2-mod-wsgi
    - libffi-dev
    - python-dev
  notify: restart apache

- shell: "apache2 -v | grep 'Apache/2.4'"
  register: apache24
  ignore_errors: True

- name: checkout source code
  git:
    repo=https://review.openstack.org/openstack/{{ item.repo }}.git
    dest=/opt/{{ item.repo }}
    force=yes
    refspec={{ item.version }}
  with_items:
    - { repo: 'keystone', version: "{{ keystone_version | default('refs/heads/master') }}"  }
    - { repo: 'keystonemiddleware', version: "{{ keystonemiddleware_version | default('refs/heads/master') }}" }
    - { repo: 'python-keystoneclient', version: "{{ keystoneclient_version | default('refs/heads/master') }}" }
  notify: restart apache

- name: create access logs
  file:
    path=/var/log/apache2/{{ item }}.access.log
    state=touch
    owner=www-data
    group=www-data
    mode=0755
  with_items:
    - keystone-admin
    - keystone-main

- name: create error logs
  file:
    path=/var/log/apache2/{{ item }}.error.log
    state=touch
    owner=www-data
    group=www-data
    mode=0755
  with_items:
    - keystone-admin
    - keystone-main

- name: remove the default virtual host
  file:
    path=/etc/apache2/sites-enabled/000-default
    state=absent
  notify: restart apache

- name: remove the default virtual host for Apache 2.4
  file:
    path=/etc/apache2/sites-enabled/000-default.conf
    state=absent
  when: apache24|success
  notify: restart apache

- name: deploy a virtual hosts
  template:
    src={{ item }}.vhost
    dest=/etc/apache2/sites-enabled/{{ item }}.conf
  with_items:
    - echo
    - keystone
  notify: restart apache

- name: establish a configuration directory for keystone
  file:
    path=/etc/keystone
    state=directory
    owner=www-data
    group=www-data
    mode=0755
  notify: restart apache

- name: create dirs for wsgi scripts
  file:
    path=/var/www/{{ item }}
    state=directory
    owner=www-data
    group=www-data
    mode=0755
  with_items:
    - echo
    - keystone
  notify: restart apache

- name: deploy keystone wsgi scripts
  template:
    src=keystone.wsgi
    dest=/var/www/keystone/{{ item }}
    owner=www-data
    group=www-data
    mode=0400
  notify: restart apache
  with_items:
    - admin
    - main

- name: deploy an echo wsgi script
  template:
    src=echo.py
    dest=/var/www/echo/echo.py
    owner=www-data
    group=www-data
    mode=0400
  notify: restart apache

- name: deploy keystone configuration files
  template:
    src={{ item }}
    dest=/etc/keystone/{{ item }}
    owner=www-data
    group=www-data
    mode=0400
  with_items:
    - keystone.conf
    - paste.ini
    - policy.json
  notify: restart apache

- name: install extra python requirements
  pip:
    name={{ item }}
    state=latest
  with_items:
    - pycrypto
    - python-memcached
    - six  # workaround for debian wheezy?
  notify: restart apache

- name: install python projects
  shell: cd /opt/{{ item }} && python setup.py install
  with_items:
    - keystone
    - keystonemiddleware
    - python-keystoneclient
  notify: restart apache

- name: run database migrations
  shell: keystone-manage db_sync
